ISOLATE_REDIS_HOST="127.0.0.1";
ISOLATE_REDIS_PORT="6379";
# ansible/roles/redis/vars/main.yml
ISOLATE_REDIS_PASS=""; 
ISOLATE_BACKEND=redis; 
export ISOLATE_BACKEND;
export ISOLATE_REDIS_HOST;
export ISOLATE_REDIS_PORT;
export ISOLATE_REDIS_PASS;