---

- name: test
  hosts: all
  become: true
  tasks:
  - name: test
    debug: 
      var: ansible_facts
    tags:
      - test
      - never

- name: Ubuntu 16.04 workarounds
  gather_facts: no
  hosts: all
  become: true
  tasks:
  - name: Installing Python...
    apt:
      update_cache: yes
      name: 
        - python
        - python-dev
        - python-pip
        - python-simplejson
      autoclean: yes
    when: ubuntu_1604 | default(False)

- name: Auth host setup...
  gather_facts: yes
  become: true
  hosts: all
  roles:
    - role: common
      tags: common

    - role: redis
      tags: redis

    - role: pam2fa
      tags: pam2fa

    - role: auth
      tags: auth

    - role: deploy
      tags: deploy

- name:  dumper
  hosts: all
  become: true
  tasks: 
    - include: dumper.yml
      tags:
        - dumper
