---
- name: Ubuntu 16.04 workarounds
  gather_facts: no
  hosts: all
  tasks:
  - name: Installing Python...
    apt:
      update_cache: yes
      name: 
        - python
        -  python-dev
        - python-pip
        - python-simplejson
      autoclean: yes
    when: ubuntu_1604 | default(False)
    tags: always

- name: Auth host setup...
  gather_facts: yes
  become_user: root
  hosts: all
  roles:
    - role: common
      tags: common

    - role: redis
      tags: redis

    - role: pam2fa
      tags: pam2fa

    - role: auth
      tags: auth

    - role: deploy
      git_repo: https://github.com/yva/isolate
      git_branch: master
      tags: deploy
